# Generated by Django 5.0.1 on 2024-06-29 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
